language: python
sudo: true
python:
  - "2.7"

addons:
  - ssh_known_hosts: localhost

env:
    - TOX_ENV=pep8
    - TOX_ENV=unittests
    - TOX_ENV=integration
    - TOX_ENV=validate-blueprints
    - TOX_ENV=cfy-local-nodecellar
    - TOX_ENV=travis-cfy-local-nodecellar-with-fabric
    - TOX_ENV=travis-cfy-local-postgresql-with-fabric
    - TOX_ENV=travis-cfy-local-score-postgresql-with-fabric

install:

    - ssh-keygen -f ~/.ssh/id_rsa -y >> ~/.ssh/id_rsa.pub
    - cat ~/.ssh/id_rsa.pub
    - cat ~/.ssh/id_rsa
    - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
    - chmod +x ~/.ssh/authorized_keys
    - echo -e "StrictHostKeyChecking no\n" >> ~/.ssh/conf

    - pip install tox

script:

    - tox -c score-api-server/tox.ini -e $TOX_ENV

after_script:

    - cat /tmp/score-api.log
