language: python
sudo: false
python:
  - "2.7"
env:
    - TOX_ENV=pep8
install:
    - pip install tox
    - pip install https://github.com/cloudify-cosmo/cloudify-rest-client/archive/3.2.zip
    - pip install https://github.com/cloudify-cosmo/cloudify-dsl-parser/archive/3.2.zip
    - pip install https://github.com/cloudify-cosmo/cloudify-plugins-common/archive/3.2.zip
    - pip install https://github.com/cloudify-cosmo/cloudify-script-plugin/archive/1.2.zip
    - pip install https://github.com/cloudify-cosmo/cloudify-cli/archive/3.2.zip
    - pip install https://github.com/cloudify-cosmo/tosca-vcloud-plugin/archive/1.2.zip

script:
    - tox -c score-api-server/tox.ini -e $TOX_ENV
    - cfy init
    - cfy blueprints validate -p blueprints/vcloud-manager-blueprint.yaml
    - cfy blueprints validate -p blueprints/postgresql-blueprint.yaml
    - cfy blueprints validate -p blueprints/vcloud-score-blueprint.yaml
    - cfy blueprints validate -p blueprints/vcloud-nodecellar-blueprint.yaml
