language: python
sudo: true
python:
  - "2.7"

addons:
  - ssh_known_hosts: localhost

env:
    - TOX_ENV=pep8
    - TOX_ENV=unittests
    - TOX_ENV=integration
    - TOX_ENV=validate-blueprints
    - TOX_ENV=vcloud-score-blueprint-local-with-fabric

install:

    - cat key-gen/key > ~/.ssh/id_rsa
    - cat key-gen/key.pub > ~/.ssh/id_rsa.pub
    - cat ~/.ssh/id_rsa.pub
    - cat ~/.ssh/id_rsa
    - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
    - chmod +x ~/.ssh/authorized_keys
    - echo -e "StrictHostKeyChecking no\n" >> ~/.ssh/conf

    - pip install tox

script:

    - tox -c score-api-server/tox.ini -e $TOX_ENV

after_script:

    - cat /tmp/score-api.log
