language: python
sudo: false
python:
  - "2.7"

addons:
    - ssh_known_hosts: localhost

env:
    - TOX_ENV=pep8
    - TOX_ENV=unittests
    - TOX_ENV=integration
    - TOX_ENV=validate-blueprints

install:

    - pip install tox

script:

    - tox -c walle-api-server/tox.ini -e $TOX_ENV

after_script:

    - cat /tmp/wally-api.log
