language: python
sudo: false
python:
  - "2.7"

addons:
  - ssh_known_hosts: localhost
  - postgresql: "9.3"

env:
    - TOX_ENV=pep8
    - TOX_ENV=unittests
    - TOX_ENV=integration
    - TOX_ENV=validate-blueprints
    - TOX_ENV=cfy-local-nodecellar
    - TOX_ENV=cfy-local-nodecellar-with-fabric
    - TOX_ENV=cfy-local-postgresql-with-fabric

install:

    - ssh-keygen -f ~/.ssh/id_rsa -y >> ~/.ssh/id_rsa.pub
    - cat ~/.ssh/id_rsa.pub
    - cat ~/.ssh/id_rsa
    - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
    - chmod +x ~/.ssh/authorized_keys
    - echo -e "StrictHostKeyChecking no\n" >> ~/.ssh/conf

    - pip install tox

before_script:
    - psql -c 'create database score;' -U postgres
    - export SCORE_DB='postgresql://postgres@localhost/score'

script:

    - tox -c score-api-server/tox.ini -e $TOX_ENV

