"""empty message

Revision ID: 24b18f82b635
Revises: 18ad57c58379
Create Date: 2015-08-05 15:39:08.537551

"""

# revision identifiers, used by Alembic.
revision = '24b18f82b635'
down_revision = '18ad57c58379'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('approved_plugins')
    op.create_table('approved_plugins',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('source', sa.String(), nullable=True),
                    sa.Column('plugin_type', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('approved_plugins')
    ### end Alembic commands ###
