"""empty message

Revision ID: 2ad5ca07a2af
Revises: 24b18f82b635
Create Date: 2016-04-28 11:54:52.336223

"""

# revision identifiers, used by Alembic.
revision = '2ad5ca07a2af'
down_revision = '24b18f82b635'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowed_ketstore_urls',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('keystore_url', sa.String(), nullable=True),
    sa.Column('info', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keystore_url')
    )
    op.create_table('keystore_url_to_cloudify_with_limits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('keystore_url', sa.String(), nullable=True),
    sa.Column('deployment_limits', sa.Integer(), nullable=True),
    sa.Column('number_of_deployments', sa.Integer(), nullable=True),
    sa.Column('cloudify_host', sa.String(), nullable=True),
    sa.Column('cloudify_port', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keystore_url')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keystore_url_to_cloudify_with_limits')
    op.drop_table('allowed_ketstore_urls')
    ### end Alembic commands ###
