"""empty message

Revision ID: 39f07a5268ab
Revises: None
Create Date: 2016-05-17 14:11:56.827465

"""

# revision identifiers, used by Alembic.
revision = '39f07a5268ab'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowed_ketstore_urls',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('keystore_url', sa.String(), nullable=True),
    sa.Column('info', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keystore_url')
    )
    op.create_table('allowed_org_ids',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('info', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id')
    )
    op.create_table('approved_plugins',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('plugin_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keystore_url_to_cloudify_with_limits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('keystore_url', sa.String(), nullable=True),
    sa.Column('deployment_limits', sa.Integer(), nullable=True),
    sa.Column('number_of_deployments', sa.Integer(), nullable=True),
    sa.Column('cloudify_host', sa.String(), nullable=True),
    sa.Column('cloudify_port', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keystore_url')
    )
    op.create_table('org_id_to_cloudify_with_limits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('deployment_limits', sa.Integer(), nullable=True),
    sa.Column('number_of_deployments', sa.Integer(), nullable=True),
    sa.Column('cloudify_host', sa.String(), nullable=True),
    sa.Column('cloudify_port', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id')
    )
    op.create_table('score_admins',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('expire', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score_admins')
    op.drop_table('org_id_to_cloudify_with_limits')
    op.drop_table('keystore_url_to_cloudify_with_limits')
    op.drop_table('approved_plugins')
    op.drop_table('allowed_org_ids')
    op.drop_table('allowed_ketstore_urls')
    ### end Alembic commands ###
