"""empty message

Revision ID: 052a4be14b22
Revises: 6befe8feae0a
Create Date: 2016-09-21 13:04:22.249504

"""

# revision identifiers, used by Alembic.
revision = '052a4be14b22'
down_revision = '6befe8feae0a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_rights',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('rights_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rights_id'], ['rights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('walle_admins')
    op.drop_table('tenant_rights')
    op.add_column('tenants', sa.Column('tenant_id', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'tenant_id')
    op.create_table('tenant_rights',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('rights_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['rights_id'], [u'rights.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], [u'tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('walle_admins',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('password', sa.VARCHAR(length=32), nullable=True),
    sa.Column('token', sa.VARCHAR(length=32), nullable=True),
    sa.Column('expire', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('user_rights')
    ### end Alembic commands ###
