"""empty message

Revision ID: 18ad57c58379
Revises: 4fa2340e9beb
Create Date: 2015-07-27 16:41:00.539919

"""

# revision identifiers, used by Alembic.
revision = '18ad57c58379'
down_revision = '4fa2340e9beb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approved_plugins',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('source', sa.String(), nullable=True),
                    sa.Column('plugin_type', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name'),
                    sa.UniqueConstraint('source')
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('approved_plugins')
    ### end Alembic commands ###
