"""empty message

Revision ID: 6859dfbb1682
Revises: 2ad5ca07a2af
Create Date: 2016-06-08 11:45:27.031751

"""

# revision identifiers, used by Alembic.
revision = '6859dfbb1682'
down_revision = '2ad5ca07a2af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_admins',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('expire', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score_admins')
    ### end Alembic commands ###
